apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: registry-pv
  resources:
    requests:
      storage: 20Gi