---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleanup-job-account
  namespace: apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cleanup-job-role
  namespace: apps
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cleanup-job-binding
  namespace: apps
subjects:
  - kind: ServiceAccount
    name: cleanup-job-account
    namespace: apps
roleRef:
  kind: Role
  name: cleanup-job-role
  apiGroup: rbac.authorization.k8s.io