apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: django-app
resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - cleanup-rbac.yaml
  - configmap.yaml
  - postgresql.yaml
  - redis.yaml
  - django-deployment.yaml
  - nginx-deployment.yaml
  - ingress.yaml
configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf
