limit_req_zone $http_cf_connecting_ip zone=api_per_ip:10m rate=20r/s;

upstream django {
    server django-service:8000;
}

server {
    listen 80;
    server_name api.melekabderrahmane.com;

    client_max_body_size 100M;

    location ~* \.(php|aspx?|jsp|cgi|env|git|sql|bak|swp|old|orig|py|yml|yaml|log|ini|conf)$ { return 444; }
    location ~* /(\.env|\.git|wp-(admin|login|json)|xmlrpc|phpmyadmin|adminer|actuator|server-status|_layouts|appsettings\.|web\.config|_debugbar|_ignition|_profiler|telescope|horizon|storage/logs|config/database\.|gateway/routes|rest/type/node|env\.json) { return 444; }

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /app/media/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $http_cf_connecting_ip;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header CF-Connecting-IP $http_cf_connecting_ip;
        proxy_redirect off;

        limit_req zone=api_per_ip burst=40 nodelay;
        limit_req_status 429;
    }
}
