apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: django-account-binding-in-apps
  namespace: apps
subjects:
- kind: ServiceAccount
  name: django-account
  namespace: django-app
roleRef:
  kind: Role
  name: django-role-in-apps
  apiGroup: rbac.authorization.k8s.io